# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_psbpHMM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_psbpHMM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_psbpHMM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_psbpHMM_rcpparma_bothproducts`, x)
}

timesTwo <- function(x) {
    .Call(`_psbpHMM_timesTwo`, x)
}

addTwo <- function(x) {
    .Call(`_psbpHMM_addTwo`, x)
}

minusTwo <- function(x) {
    .Call(`_psbpHMM_minusTwo`, x)
}

a1 <- function(x) {
    .Call(`_psbpHMM_a1`, x)
}

a2 <- function(x) {
    .Call(`_psbpHMM_a2`, x)
}

a8 <- function(n, r, v) {
    .Call(`_psbpHMM_a8`, n, r, v)
}

mhDecomp <- function(L, D) {
    .Call(`_psbpHMM_mhDecomp`, L, D)
}

invMat <- function(x) {
    .Call(`_psbpHMM_invMat`, x)
}

updatePi <- function(beta, X, a0, ajk, tmax) {
    .Call(`_psbpHMM_updatePi`, beta, X, a0, ajk, tmax)
}

updatePi2 <- function(beta, X, a0, ajk, tmax) {
    .Call(`_psbpHMM_updatePi2`, beta, X, a0, ajk, tmax)
}

returnPi <- function() {
    .Call(`_psbpHMM_returnPi`)
}

mvndensity <- function(y, mu, Sigma, d) {
    .Call(`_psbpHMM_mvndensity`, y, mu, Sigma, d)
}

upZ <- function(stateList, y, mu, Sigma, logStuff, nudf, detRstar, piz, u, tmax, K, n, d) {
    .Call(`_psbpHMM_upZ`, stateList, y, mu, Sigma, logStuff, nudf, detRstar, piz, u, tmax, K, n, d)
}

fun10 <- function(piz, u, stateList, K, jprime, jprobs) {
    .Call(`_psbpHMM_fun10`, piz, u, stateList, K, jprime, jprobs)
}

testClear <- function() {
    .Call(`_psbpHMM_testClear`)
}

csample_num <- function(x, size, replace, prob = as.numeric( c())) {
    .Call(`_psbpHMM_csample_num`, x, size, replace, prob)
}

csample_int <- function(x, size, replace, prob = as.numeric( c())) {
    .Call(`_psbpHMM_csample_int`, x, size, replace, prob)
}

a3 <- function(x) {
    .Call(`_psbpHMM_a3`, x)
}

a4 <- function(x) {
    .Call(`_psbpHMM_a4`, x)
}

