# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_psbpHMM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_psbpHMM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_psbpHMM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_psbpHMM_rcpparma_bothproducts`, x)
}

mhDecomp <- function(L, D) {
    .Call(`_psbpHMM_mhDecomp`, L, D)
}

invMat <- function(x) {
    .Call(`_psbpHMM_invMat`, x)
}

updatePi <- function(beta, X, a0, ajk, tmax) {
    .Call(`_psbpHMM_updatePi`, beta, X, a0, ajk, tmax)
}

updatePi_rm <- function(beta, beta_sk, X, a0, ajk, tmax) {
    .Call(`_psbpHMM_updatePi_rm`, beta, beta_sk, X, a0, ajk, tmax)
}

returnPi <- function() {
    .Call(`_psbpHMM_returnPi`)
}

mvndensity <- function(y, mu, Sigma, d) {
    .Call(`_psbpHMM_mvndensity`, y, mu, Sigma, d)
}

upZ <- function(stateList, y, mu, Sigma, logStuff, nudf, detRstar, piz, u, tmax, K, n, d) {
    .Call(`_psbpHMM_upZ`, stateList, y, mu, Sigma, logStuff, nudf, detRstar, piz, u, tmax, K, n, d)
}

upStateList <- function(piz, u, K, tmax, n) {
    .Call(`_psbpHMM_upStateList`, piz, u, K, tmax, n)
}

createMat <- function(n, niter, Zmat) {
    .Call(`_psbpHMM_createMat`, n, niter, Zmat)
}

vectorMean <- function(a, b) {
    .Call(`_psbpHMM_vectorMean`, a, b)
}

